# Generated by Django 2.2 on 2019-04-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HumidityMeassurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sample_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureMeassurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sample_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
