# Generated by Django 3.1.3 on 2020-12-02 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.TextField(max_length=12, verbose_name='Sensor Type')),
                ('Description', models.TextField(max_length=30, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShortName', models.TextField(max_length=12, verbose_name='Short Name')),
                ('Description', models.TextField(max_length=30, verbose_name='Description')),
                ('CreationDate', models.TimeField(verbose_name='Creation Date')),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sensor.sensortype')),
            ],
        ),
    ]
