# Generated by Django 3.1.3 on 2020-12-02 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sensor', '0002_sensor_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(verbose_name='Date')),
                ('Value', models.IntegerField(verbose_name='Value')),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sensor.sensor')),
            ],
        ),
    ]
