# Generated by Django 3.1.3 on 2020-12-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensor', '0003_measurement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='Type',
            new_name='Sensor',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='CreationDate',
            field=models.DateTimeField(verbose_name='Creation Date'),
        ),
    ]
