# Generated by Django 3.1.3 on 2020-12-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensor', '0004_auto_20201202_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='State',
            field=models.CharField(choices=[('Y', 'Active'), ('N', 'Inactive')], default='Y', max_length=1),
        ),
    ]
