# Generated by Django 3.1.3 on 2020-12-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensor', '0006_auto_20201202_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='Description',
            field=models.TextField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='ShortName',
            field=models.TextField(max_length=40, verbose_name='Short Name'),
        ),
    ]
